// patterns/behavioral/strategy/react/App.tsx
/**
 * Strategy 패턴 — React 구현
 *
 * React에서의 역할 매핑:
 * - Strategy (SortStrategy 인터페이스) → SortStrategy 타입 (함수 + 이름)
 * - ConcreteStrategy                   → bubbleSort, quickSort, mergeSortFn 함수들
 * - Context (Sorter)                   → useSorter() 훅 (전략을 교체하고 실행)
 *
 * 왜 함수를 전략으로 쓰는가?
 * - TS에서 ConcreteStrategy는 sort() 메서드를 가진 클래스였다.
 * - React/함수형 프로그래밍에서는 함수 자체가 전략이다.
 * - setStrategy(bubbleSort) 한 줄로 런타임에 전략을 교체한다.
 * - 이는 TS의 sorter.setStrategy(new BubbleSortStrategy())와 완전히 동일하다.
 */

import { useState, useCallback } from 'react'

// ─────────────────────────────────────────────
// Strategy 타입 — 함수로 표현된 전략
// ─────────────────────────────────────────────

interface SortStrategy {
  name: string
  description: string
  sort: (data: number[]) => number[]
  complexity: string
  color: string
}

// ─────────────────────────────────────────────
// ConcreteStrategy 함수들
// ─────────────────────────────────────────────

/**
 * ConcreteStrategy 1: 버블 정렬
 * 인접 요소를 비교/교환하는 O(n²) 알고리즘.
 */
const bubbleSortStrategy: SortStrategy = {
  name: '버블 정렬',
  description: '인접한 두 요소를 비교하며 교환합니다.',
  complexity: 'O(n²)',
  color: '#1976d2',
  sort(data: number[]): number[] {
    const arr = [...data]
    const n = arr.length
    for (let i = 0; i < n - 1; i++) {
      for (let j = 0; j < n - 1 - i; j++) {
        if (arr[j] > arr[j + 1]) {
          [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]]
        }
      }
    }
    return arr
  },
}

/**
 * ConcreteStrategy 2: 퀵 정렬
 * 피벗 기준 분할 정복, 평균 O(n log n).
 */
const quickSortStrategy: SortStrategy = {
  name: '퀵 정렬',
  description: '피벗을 기준으로 분할 정복합니다.',
  complexity: 'O(n log n)',
  color: '#388e3c',
  sort(data: number[]): number[] {
    const arr = [...data]
    function qs(low: number, high: number) {
      if (low >= high) return
      const pivot = arr[high]
      let i = low - 1
      for (let j = low; j < high; j++) {
        if (arr[j] <= pivot) { i++; [arr[i], arr[j]] = [arr[j], arr[i]] }
      }
      [arr[i + 1], arr[high]] = [arr[high], arr[i + 1]]
      const pi = i + 1
      qs(low, pi - 1)
      qs(pi + 1, high)
    }
    qs(0, arr.length - 1)
    return arr
  },
}

/**
 * ConcreteStrategy 3: 머지 정렬
 * 분할 후 병합, 안정적인 O(n log n).
 */
const mergeSortStrategy: SortStrategy = {
  name: '머지 정렬',
  description: '배열을 반씩 나눠 정렬 후 병합합니다.',
  complexity: 'O(n log n)',
  color: '#f57c00',
  sort(data: number[]): number[] {
    function ms(arr: number[]): number[] {
      if (arr.length <= 1) return arr
      const mid = Math.floor(arr.length / 2)
      const left = ms(arr.slice(0, mid))
      const right = ms(arr.slice(mid))
      const result: number[] = []
      let i = 0, j = 0
      while (i < left.length && j < right.length) {
        result.push(left[i] <= right[j] ? left[i++] : right[j++])
      }
      return result.concat(left.slice(i)).concat(right.slice(j))
    }
    return ms([...data])
  },
}

/**
 * ConcreteStrategy 4: 내장 정렬 (JavaScript 기본)
 */
const nativeSortStrategy: SortStrategy = {
  name: 'JS 기본 정렬',
  description: 'JavaScript 내장 Array.sort()를 사용합니다.',
  complexity: 'O(n log n)',
  color: '#7b1fa2',
  sort(data: number[]): number[] {
    return [...data].sort((a, b) => a - b)
  },
}

const ALL_STRATEGIES = [bubbleSortStrategy, quickSortStrategy, mergeSortStrategy, nativeSortStrategy]

// ─────────────────────────────────────────────
// Context 훅 — Sorter 역할
// ─────────────────────────────────────────────

/**
 * useSorter: Context 역할을 하는 훅.
 *
 * TS의 Sorter 클래스가 strategy를 내부에 보관하고
 * setStrategy()로 런타임에 교체했듯이,
 * 이 훅은 currentStrategy state를 관리하고 sort()를 실행한다.
 */
function useSorter(initial: SortStrategy = bubbleSortStrategy) {
  // 현재 전략 — 런타임에 교체 가능
  const [currentStrategy, setCurrentStrategy] = useState<SortStrategy>(initial)
  const [data, setData] = useState<number[]>([64, 34, 25, 12, 22, 11, 90])
  const [sortedData, setSortedData] = useState<number[] | null>(null)
  const [sortTime, setSortTime] = useState<number>(0)
  const [log, setLog] = useState<string[]>([])

  /**
   * sort(): 현재 전략으로 데이터를 정렬한다.
   * 전략이 교체되어도 이 함수는 변경되지 않는다 — Context의 핵심.
   */
  const sort = useCallback(() => {
    const start = performance.now()
    // 전략에게 위임 — 어떤 알고리즘인지 Context는 모른다
    const result = currentStrategy.sort(data)
    const elapsed = performance.now() - start
    setSortedData(result)
    setSortTime(elapsed)
    setLog(prev => [
      `[${currentStrategy.name}] [${data.join(', ')}] → [${result.join(', ')}] (${elapsed.toFixed(3)}ms)`,
      ...prev.slice(0, 4),
    ])
  }, [currentStrategy, data])

  const randomize = useCallback(() => {
    const arr = Array.from({ length: 8 }, () => Math.floor(Math.random() * 100))
    setData(arr)
    setSortedData(null)
  }, [])

  return {
    currentStrategy,
    setStrategy: setCurrentStrategy, // Sorter.setStrategy()에 해당
    data, setData, sortedData, sortTime, sort, randomize, log,
  }
}

// ─────────────────────────────────────────────
// 배열 시각화 컴포넌트
// ─────────────────────────────────────────────

function ArrayBar({ values, color, label }: { values: number[]; color: string; label: string }) {
  const max = Math.max(...values)
  return (
    <div>
      <div style={{ fontSize: 12, color: '#888', marginBottom: 4 }}>{label}</div>
      <div style={{ display: 'flex', gap: 4, alignItems: 'flex-end', height: 80 }}>
        {values.map((v, i) => (
          <div key={i} style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
            <div style={{
              width: '100%', background: color, borderRadius: '3px 3px 0 0',
              height: `${(v / max) * 70}px`, minHeight: 4,
            }} />
            <div style={{ fontSize: 10, color: '#555', marginTop: 2 }}>{v}</div>
          </div>
        ))}
      </div>
    </div>
  )
}

// ─────────────────────────────────────────────
// 메인 App
// ─────────────────────────────────────────────

export default function App() {
  const sorter = useSorter()

  return (
    <div style={{ fontFamily: 'sans-serif', maxWidth: 750, margin: '40px auto', padding: '0 20px' }}>
      <h1 style={{ fontSize: 24, marginBottom: 8 }}>Strategy 패턴 — React</h1>
      <p style={{ color: '#666', marginBottom: 24, fontSize: 14 }}>
        정렬 전략을 런타임에 교체합니다. Context(useSorter)는 어떤 알고리즘인지 모르고 전략에게 위임합니다.
      </p>

      {/* 전략 선택 */}
      <div style={{ marginBottom: 20 }}>
        <div style={{ fontWeight: 'bold', fontSize: 13, marginBottom: 8 }}>
          전략 선택 — Sorter.setStrategy() 호출
        </div>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          {ALL_STRATEGIES.map(s => (
            <button key={s.name} onClick={() => sorter.setStrategy(s)}
              style={{
                padding: '8px 16px', borderRadius: 6, border: `2px solid ${s.color}`, cursor: 'pointer', fontSize: 13,
                background: sorter.currentStrategy.name === s.name ? s.color : 'white',
                color: sorter.currentStrategy.name === s.name ? 'white' : s.color,
                fontWeight: sorter.currentStrategy.name === s.name ? 'bold' : 'normal',
              }}>
              {s.name}
              <span style={{ marginLeft: 6, fontSize: 11, opacity: 0.8 }}>{s.complexity}</span>
            </button>
          ))}
        </div>
        <div style={{ marginTop: 8, fontSize: 12, color: '#666', background: '#f5f5f5', padding: '6px 12px', borderRadius: 4, display: 'inline-block' }}>
          현재 전략: <strong style={{ color: sorter.currentStrategy.color }}>{sorter.currentStrategy.name}</strong> — {sorter.currentStrategy.description}
        </div>
      </div>

      {/* 데이터 입력 */}
      <div style={{ marginBottom: 16, background: '#f9f9f9', padding: 16, borderRadius: 8 }}>
        <div style={{ fontWeight: 'bold', fontSize: 13, marginBottom: 8 }}>정렬할 데이터</div>
        <div style={{ display: 'flex', gap: 8, marginBottom: 12 }}>
          <input
            value={sorter.data.join(', ')}
            onChange={e => {
              const nums = e.target.value.split(',').map(s => parseInt(s.trim())).filter(n => !isNaN(n))
              sorter.setData(nums)
              // 데이터 변경 시 결과 초기화
            }}
            style={{ flex: 1, padding: '8px 12px', border: '1px solid #ddd', borderRadius: 6, fontSize: 13, fontFamily: 'monospace' }}
          />
          <button onClick={sorter.randomize}
            style={{ padding: '8px 16px', background: '#607d8b', color: 'white', border: 'none', borderRadius: 6, cursor: 'pointer' }}>
            랜덤
          </button>
        </div>

        <ArrayBar values={sorter.data} color={sorter.currentStrategy.color} label="정렬 전" />

        <div style={{ margin: '12px 0' }}>
          <button onClick={sorter.sort}
            style={{
              padding: '10px 28px', background: sorter.currentStrategy.color,
              color: 'white', border: 'none', borderRadius: 6, cursor: 'pointer', fontWeight: 'bold',
            }}>
            sort() 실행 ({sorter.currentStrategy.name})
          </button>
          {sorter.sortTime > 0 && (
            <span style={{ marginLeft: 12, fontSize: 12, color: '#888' }}>
              실행 시간: {sorter.sortTime.toFixed(3)}ms
            </span>
          )}
        </div>

        {sorter.sortedData && (
          <ArrayBar values={sorter.sortedData} color={sorter.currentStrategy.color} label="정렬 후" />
        )}
      </div>

      {/* 실행 로그 */}
      {sorter.log.length > 0 && (
        <div style={{ background: '#1a1a1a', color: '#a5d6a7', padding: 12, borderRadius: 6, fontSize: 12, fontFamily: 'monospace', marginBottom: 16 }}>
          <div style={{ color: '#888', marginBottom: 4 }}>실행 이력 (전략 변경 추적):</div>
          {sorter.log.map((l, i) => <div key={i}>{l}</div>)}
        </div>
      )}

      <div style={{ background: '#fff8e1', padding: 16, borderRadius: 8, fontSize: 13 }}>
        <strong>패턴 포인트:</strong>
        <ul style={{ margin: '8px 0 0', paddingLeft: 20 }}>
          <li><code>useSorter()</code>가 Context — 어떤 알고리즘인지 모르고 <code>strategy.sort()</code>에 위임한다</li>
          <li>전략 버튼 클릭 = <code>setStrategy()</code> — if/else 없이 런타임에 알고리즘 교체</li>
          <li>새 정렬 알고리즘 추가 시 <code>SortStrategy</code> 객체만 만들면 된다 — Context 코드 무변경</li>
          <li>실행 로그에서 전략 교체가 이력에 기록되는 것을 확인할 수 있다</li>
        </ul>
      </div>
    </div>
  )
}

// patterns/behavioral/strategy/vue/App.vue
<script setup lang="ts">
/**
 * Strategy 패턴 — Vue 구현
 *
 * Vue에서의 역할 매핑:
 *   SortStrategy (인터페이스)   → 정렬 함수 타입: (data: number[]) => number[]
 *   ConcreteStrategy들          → ref에 저장된 전략 함수들 (버블/퀵/머지 정렬)
 *   currentStrategy (ref)       → Context: 현재 전략을 저장하는 ref
 *   computed(sorted)            → 전략 교체 시 자동으로 재계산되는 정렬 결과
 *
 * 왜 이렇게 구현하는가?
 *   TypeScript 버전의 Sorter 클래스(Context)를 Vue에서는 ref로 교체 가능한 전략 함수로 표현한다.
 *   ref에 저장된 함수를 교체하면 computed가 자동으로 새 전략으로 재계산한다.
 *   if/else 없이 알고리즘을 동적으로 교체하는 Strategy 패턴의 핵심을 그대로 구현한다.
 */

import { ref, computed, reactive } from 'vue'

// ─── Strategy 타입 ────────────────────────────────────────────────────────────
interface SortStrategy {
  name: string
  sort: (data: number[]) => number[]
  description: string
}

// ─── ConcreteStrategy 구현체들 ────────────────────────────────────────────────
// 각각은 TypeScript 버전의 BubbleSortStrategy, QuickSortStrategy, MergeSortStrategy에 해당한다.

/** 버블 정렬 전략 */
const bubbleSort: SortStrategy = {
  name: '버블 정렬',
  description: 'O(n²) — 인접한 두 요소를 비교하며 교환',
  sort(data: number[]) {
    const arr = [...data]
    const n = arr.length
    for (let i = 0; i < n - 1; i++) {
      for (let j = 0; j < n - 1 - i; j++) {
        if (arr[j] > arr[j + 1]) {
          ;[arr[j], arr[j + 1]] = [arr[j + 1], arr[j]]
        }
      }
    }
    return arr
  },
}

/** 퀵 정렬 전략 */
const quickSort: SortStrategy = {
  name: '퀵 정렬',
  description: 'O(n log n) 평균 — 피벗 기준 분할 정복',
  sort(data: number[]) {
    const arr = [...data]
    function qs(a: number[], lo: number, hi: number) {
      if (lo >= hi) return
      const pivot = a[hi]
      let i = lo - 1
      for (let j = lo; j < hi; j++) {
        if (a[j] <= pivot) { i++; [a[i], a[j]] = [a[j], a[i]] }
      }
      ;[a[i + 1], a[hi]] = [a[hi], a[i + 1]]
      const p = i + 1
      qs(a, lo, p - 1)
      qs(a, p + 1, hi)
    }
    qs(arr, 0, arr.length - 1)
    return arr
  },
}

/** 머지 정렬 전략 */
const mergeSort: SortStrategy = {
  name: '머지 정렬',
  description: 'O(n log n) 안정 — 배열을 반씩 나눠 병합',
  sort(data: number[]) {
    function ms(arr: number[]): number[] {
      if (arr.length <= 1) return arr
      const mid = Math.floor(arr.length / 2)
      const left = ms(arr.slice(0, mid))
      const right = ms(arr.slice(mid))
      const result: number[] = []
      let i = 0, j = 0
      while (i < left.length && j < right.length) {
        result.push(left[i] <= right[j] ? left[i++] : right[j++])
      }
      return result.concat(left.slice(i)).concat(right.slice(j))
    }
    return ms([...data])
  },
}

/** 역방향 정렬 전략 (보너스 전략) */
const reverseSort: SortStrategy = {
  name: '역방향 정렬',
  description: 'O(n log n) — 내림차순 정렬',
  sort(data: number[]) {
    return [...data].sort((a, b) => b - a)
  },
}

const strategies: SortStrategy[] = [bubbleSort, quickSort, mergeSort, reverseSort]

// ─── Context: 현재 전략을 ref로 관리 ─────────────────────────────────────────
// TypeScript 버전의 Sorter 클래스에서 this.strategy = strategy와 동일
// ref에 저장된 함수를 바꾸는 것이 "전략 교체"다
const currentStrategy = ref<SortStrategy>(quickSort)

// 데이터
const inputData = ref([64, 34, 25, 12, 22, 11, 90, 45, 8, 73])
const dataInput = ref('64, 34, 25, 12, 22, 11, 90, 45, 8, 73')
const sortTime = ref(0)

// ─── computed: 현재 전략으로 자동 정렬 ───────────────────────────────────────
// 전략이 바뀌거나 입력 데이터가 바뀌면 자동으로 재계산된다.
// Context.sort()를 computed로 구현한 것이다.
const sortedData = computed(() => {
  const start = performance.now()
  const result = currentStrategy.value.sort(inputData.value)
  sortTime.value = Math.round((performance.now() - start) * 1000) / 1000
  return result
})

function applyInput() {
  const nums = dataInput.value
    .split(',')
    .map(s => parseInt(s.trim()))
    .filter(n => !isNaN(n))
  if (nums.length > 0) inputData.value = nums
}

function randomize() {
  const arr = Array.from({ length: 12 }, () => Math.floor(Math.random() * 100) + 1)
  inputData.value = arr
  dataInput.value = arr.join(', ')
}

// 각 요소에 대한 최대값 (시각화 막대 높이 계산용)
const maxValue = computed(() => Math.max(...inputData.value))
</script>

<template>
  <div style="font-family: sans-serif; max-width: 750px; margin: 2rem auto; padding: 0 1rem;">
    <h1 style="border-bottom: 2px solid #333; padding-bottom: 0.5rem;">Strategy 패턴</h1>
    <p style="color: #555;">
      정렬 전략을 <code>ref</code>에 저장한다. 버튼으로 전략을 교체하면 <code>computed</code>가
      자동으로 새 알고리즘으로 재계산한다. if/else 없이 런타임에 알고리즘을 교체한다.
    </p>

    <!-- 전략 선택 (Context.setStrategy()) -->
    <div style="margin-bottom: 1.5rem;">
      <div style="font-weight: bold; margin-bottom: 0.5rem;">전략 선택 (currentStrategy 교체):</div>
      <div style="display: flex; gap: 0.75rem; flex-wrap: wrap;">
        <button
          v-for="strategy in strategies"
          :key="strategy.name"
          @click="currentStrategy = strategy"
          :style="{
            padding: '8px 16px', cursor: 'pointer', borderRadius: '6px',
            border: '2px solid',
            borderColor: currentStrategy.name === strategy.name ? '#2b6cb0' : '#ddd',
            background: currentStrategy.name === strategy.name ? '#ebf8ff' : 'white',
            fontWeight: currentStrategy.name === strategy.name ? 'bold' : 'normal',
            transition: 'all 0.15s',
          }"
        >
          {{ strategy.name }}
        </button>
      </div>
      <div style="margin-top: 0.5rem; font-size: 0.85rem; color: #555;">
        현재: <strong>{{ currentStrategy.name }}</strong> — {{ currentStrategy.description }}
      </div>
    </div>

    <!-- 데이터 입력 -->
    <div style="display: flex; gap: 0.5rem; margin-bottom: 1.5rem; align-items: flex-end; flex-wrap: wrap;">
      <div style="flex: 1;">
        <label style="font-size: 0.85rem; font-weight: bold; display: block; margin-bottom: 4px;">입력 데이터 (쉼표 구분)</label>
        <input v-model="dataInput" @keydown.enter="applyInput"
          style="width: 100%; box-sizing: border-box; padding: 8px; border: 1px solid #ccc; border-radius: 4px;" />
      </div>
      <button @click="applyInput" style="padding: 8px 14px; cursor: pointer; border-radius: 4px; border: 1px solid #ccc; white-space: nowrap;">적용</button>
      <button @click="randomize" style="padding: 8px 14px; cursor: pointer; border-radius: 4px; border: 1px solid #ccc; white-space: nowrap;">랜덤</button>
    </div>

    <!-- 시각화 -->
    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; margin-bottom: 1.5rem;">
      <!-- 정렬 전 -->
      <div>
        <div style="font-weight: bold; margin-bottom: 0.5rem;">정렬 전</div>
        <div style="display: flex; align-items: flex-end; gap: 3px; height: 80px; border-bottom: 1px solid #ddd; padding-bottom: 2px;">
          <div
            v-for="(v, i) in inputData"
            :key="i"
            :style="{
              flex: 1, background: '#e2e8f0',
              height: `${(v / maxValue) * 100}%`,
              borderRadius: '2px 2px 0 0',
              minWidth: '4px',
            }"
            :title="String(v)"
          />
        </div>
        <div style="display: flex; gap: 3px; margin-top: 4px; font-size: 0.7rem; color: #888; flex-wrap: wrap;">
          <span v-for="(v, i) in inputData" :key="i">{{ v }}</span>
        </div>
      </div>

      <!-- 정렬 후 -->
      <div>
        <div style="font-weight: bold; margin-bottom: 0.5rem;">
          정렬 후 ({{ currentStrategy.name }}) — {{ sortTime }}ms
        </div>
        <div style="display: flex; align-items: flex-end; gap: 3px; height: 80px; border-bottom: 1px solid #ddd; padding-bottom: 2px;">
          <div
            v-for="(v, i) in sortedData"
            :key="i"
            :style="{
              flex: 1, background: '#4299e1',
              height: `${(v / maxValue) * 100}%`,
              borderRadius: '2px 2px 0 0',
              minWidth: '4px',
            }"
            :title="String(v)"
          />
        </div>
        <div style="display: flex; gap: 3px; margin-top: 4px; font-size: 0.7rem; color: #2b6cb0; flex-wrap: wrap;">
          <span v-for="(v, i) in sortedData" :key="i">{{ v }}</span>
        </div>
      </div>
    </div>

    <div style="background: #fffbeb; border: 1px solid #f6e05e; border-radius: 6px; padding: 0.75rem; font-size: 0.85rem; color: #744210;">
      <strong>패턴 포인트:</strong> 전략 버튼을 클릭하면 <code>currentStrategy ref</code>가 교체되고,
      <code>computed(sortedData)</code>가 새 전략으로 자동 재계산된다.
      Context(Sorter) 코드는 전혀 변경하지 않는다.
    </div>
  </div>
</template>
