// patterns/structural/composite/vue/App.vue
<script setup lang="ts">
/**
 * Composite 패턴 — Vue 구현
 *
 * Vue에서의 역할 매핑:
 *   FileTreeNode (재귀 컴포넌트) → Component + Composite + Leaf 모두 담당
 *   type === 'folder'             → Composite: 자식을 가질 수 있는 복합 요소
 *   type === 'file'               → Leaf: 자식이 없는 최소 단위
 *   App.vue                       → Client: 트리 루트만 렌더링, 내부 구조를 신경 안 씀
 *
 * TypeScript 버전과의 차이:
 *   - TypeScript: File 클래스와 Folder 클래스를 각각 정의
 *   - Vue: 하나의 재귀 컴포넌트(FileTreeNode)가 두 역할을 모두 처리
 *   - 데이터(FileNode 인터페이스)가 구조를 정의하고, 컴포넌트는 재귀적으로 렌더링
 */

import { ref, computed } from 'vue'
import FileTreeNode, { type FileNode } from './FileTreeNode.vue'

// ─── 파일 시스템 트리 데이터 (Composite 구조) ─────────────────────────────────
// Folder(Composite)는 children을 가지고, File(Leaf)는 children이 없다.
// 클라이언트(App.vue)는 루트 노드만 알면 되고 깊이는 신경 쓰지 않는다.
const fileTree = ref<FileNode>({
  name: 'my-project',
  type: 'folder',
  children: [
    {
      name: 'src',
      type: 'folder',
      children: [
        {
          name: 'components',
          type: 'folder',
          children: [
            { name: 'Header.vue', type: 'file', size: 2048 },
            { name: 'Footer.vue', type: 'file', size: 1536 },
            { name: 'Button.vue', type: 'file', size: 4096 },
          ],
        },
        {
          name: 'composables',
          type: 'folder',
          children: [
            { name: 'useAuth.ts', type: 'file', size: 8192 },
            { name: 'useApi.ts', type: 'file', size: 12288 },
          ],
        },
        { name: 'App.vue', type: 'file', size: 5120 },
        { name: 'main.ts', type: 'file', size: 512 },
      ],
    },
    {
      name: 'public',
      type: 'folder',
      children: [
        { name: 'favicon.ico', type: 'file', size: 4096 },
        { name: 'logo.png', type: 'file', size: 1048576 },
      ],
    },
    { name: 'package.json', type: 'file', size: 1024 },
    { name: 'vite.config.ts', type: 'file', size: 768 },
    { name: 'README.md', type: 'file', size: 2048 },
  ],
})

// ─── 전체 통계 계산 (재귀적으로 파일 수와 크기 계산) ──────────────────────────
function countFiles(node: FileNode): number {
  if (node.type === 'file') return 1
  return (node.children ?? []).reduce((acc, child) => acc + countFiles(child), 0)
}

function getTotalSize(node: FileNode): number {
  if (node.type === 'file') return node.size ?? 0
  return (node.children ?? []).reduce((acc, child) => acc + getTotalSize(child), 0)
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes}B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)}MB`
}

const totalFiles = computed(() => countFiles(fileTree.value))
const totalSize = computed(() => formatSize(getTotalSize(fileTree.value)))

// ─── 파일 추가 기능 (Composite에 Leaf 추가) ────────────────────────────────────
const newFileName = ref('')
const newFileSize = ref(1024)

function addFileToRoot() {
  if (!newFileName.value.trim()) return
  if (!fileTree.value.children) fileTree.value.children = []
  fileTree.value.children.push({
    name: newFileName.value.trim(),
    type: 'file',
    size: newFileSize.value,
  })
  newFileName.value = ''
  newFileSize.value = 1024
}
</script>

<template>
  <div style="font-family: sans-serif; max-width: 700px; margin: 2rem auto; padding: 0 1rem;">
    <h1 style="border-bottom: 2px solid #333; padding-bottom: 0.5rem;">Composite 패턴</h1>
    <p style="color: #555;">
      <code>FileTreeNode</code>는 재귀 컴포넌트다. 노드가 폴더이면 자식에게 자기 자신을 재귀 렌더링하고,
      파일이면 렌더링을 멈춘다. 클라이언트(App.vue)는 트리 깊이를 몰라도 루트 노드만 전달하면 된다.
    </p>

    <!-- 통계 -->
    <div style="display: flex; gap: 1.5rem; margin-bottom: 1.5rem; background: #f5f5f5; padding: 0.75rem 1rem; border-radius: 6px; font-size: 0.9rem;">
      <span>총 파일 수: <strong>{{ totalFiles }}개</strong></span>
      <span>총 크기: <strong>{{ totalSize }}</strong></span>
    </div>

    <!-- 파일 추가 -->
    <div style="border: 1px solid #ddd; border-radius: 6px; padding: 1rem; margin-bottom: 1.5rem; display: flex; gap: 0.5rem; align-items: flex-end; flex-wrap: wrap;">
      <div>
        <label style="font-size: 0.8rem; font-weight: bold; display: block; margin-bottom: 4px;">파일명</label>
        <input v-model="newFileName" placeholder="newfile.ts" style="padding: 6px; border: 1px solid #ccc; border-radius: 4px;" />
      </div>
      <div>
        <label style="font-size: 0.8rem; font-weight: bold; display: block; margin-bottom: 4px;">크기(bytes)</label>
        <input type="number" v-model="newFileSize" style="padding: 6px; border: 1px solid #ccc; border-radius: 4px; width: 100px;" />
      </div>
      <button @click="addFileToRoot" style="padding: 7px 14px; cursor: pointer; border-radius: 4px; border: 1px solid #ccc; background: #f0f9ff;">
        루트에 파일 추가
      </button>
      <span style="font-size: 0.8rem; color: #888;">추가하면 총 크기와 파일 수가 즉시 반영됩니다</span>
    </div>

    <!-- 파일 트리 -->
    <!-- Client는 루트 노드만 전달한다. 내부 구조는 FileTreeNode가 재귀적으로 처리한다. -->
    <div style="border: 1px solid #ddd; border-radius: 8px; padding: 1rem; font-size: 0.9rem;">
      <FileTreeNode :node="fileTree" :depth="0" />
    </div>

    <div style="margin-top: 1rem; padding: 0.75rem; background: #fffbeb; border: 1px solid #f6e05e; border-radius: 6px; font-size: 0.85rem; color: #744210;">
      <strong>패턴 포인트:</strong> 폴더를 클릭해 펼치고 닫을 수 있습니다.
      폴더의 크기는 자식 파일/폴더 크기의 합산입니다 (재귀 계산).
      클라이언트는 트리 깊이나 파일/폴더 구분을 신경 쓰지 않아도 됩니다.
    </div>
  </div>
</template>

// patterns/structural/composite/svelte/App.svelte
<script lang="ts">
  // ─────────────────────────────────────────────────────────────────────────────
  // Composite 패턴 — Svelte 5 runes 구현
  //
  // 역할 매핑:
  //   FileSystemNode 타입       → Component 인터페이스 (Leaf/Composite 공통)
  //   type: 'file'              → Leaf (자식 없는 최소 단위)
  //   type: 'folder'            → Composite (자식을 가지는 복합 요소)
  //   <svelte:self>             → 재귀 컴포넌트 (Composite의 재귀 구조 표현)
  //
  // 핵심 아이디어:
  //   TypeScript에서는 클래스 상속으로 File/Folder를 구현했지만,
  //   Svelte에서는 <svelte:self>를 사용한 재귀 컴포넌트로
  //   트리 구조를 자연스럽게 렌더링한다.
  //   getSize() 같은 재귀 연산은 재귀 함수로 구현한다.
  // ─────────────────────────────────────────────────────────────────────────────

  // ── Component 타입: Leaf와 Composite 모두가 구현하는 공통 구조 ──────────
  type FileNode = {
    id: string
    name: string
    type: 'file'
    size: number // 바이트
  }

  type FolderNode = {
    id: string
    name: string
    type: 'folder'
    children: FileSystemNode[]
    expanded: boolean
  }

  type FileSystemNode = FileNode | FolderNode

  // ── 재귀 함수들 (Composite 패턴의 위임 로직) ─────────────────────────────

  // 크기 계산: 파일이면 자신의 크기, 폴더면 모든 자식의 크기 합계 (재귀)
  function getSize(node: FileSystemNode): number {
    if (node.type === 'file') return node.size
    // Composite의 핵심: 자식들에게 같은 연산을 위임한다
    return node.children.reduce((sum, child) => sum + getSize(child), 0)
  }

  function formatSize(bytes: number): string {
    if (bytes < 1024) return `${bytes}B`
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`
    return `${(bytes / (1024 * 1024)).toFixed(1)}MB`
  }

  // 파일 수 계산 (재귀)
  function countFiles(node: FileSystemNode): number {
    if (node.type === 'file') return 1
    return node.children.reduce((sum, child) => sum + countFiles(child), 0)
  }

  // 고유 ID 생성
  let nextId = 1
  function genId() { return `node-${nextId++}` }

  // ── $state: 파일 시스템 트리 (Composite 구조) ─────────────────────────────
  let tree = $state<FolderNode>({
    id: genId(),
    name: 'project',
    type: 'folder',
    expanded: true,
    children: [
      {
        id: genId(), name: 'src', type: 'folder', expanded: true,
        children: [
          { id: genId(), name: 'App.svelte', type: 'file', size: 4096 },
          { id: genId(), name: 'main.ts', type: 'file', size: 512 },
          {
            id: genId(), name: 'components', type: 'folder', expanded: false,
            children: [
              { id: genId(), name: 'Button.svelte', type: 'file', size: 2048 },
              { id: genId(), name: 'Modal.svelte', type: 'file', size: 3072 },
            ],
          },
        ],
      },
      {
        id: genId(), name: 'public', type: 'folder', expanded: false,
        children: [
          { id: genId(), name: 'favicon.svg', type: 'file', size: 1024 },
          { id: genId(), name: 'robots.txt', type: 'file', size: 128 },
        ],
      },
      { id: genId(), name: 'package.json', type: 'file', size: 768 },
      { id: genId(), name: 'README.md', type: 'file', size: 2560 },
    ],
  })

  // $derived: 전체 크기와 파일 수 (재귀 연산 자동 재계산)
  let totalSize = $derived(formatSize(getSize(tree)))
  let totalFiles = $derived(countFiles(tree))

  // ── 폴더 토글 (expanded 상태 변경) ───────────────────────────────────────
  function toggleFolder(node: FolderNode) {
    node.expanded = !node.expanded
  }

  // 새 파일 추가
  let newFileName = $state('')
  let newFileSize = $state(1024)
  let selectedFolderId = $state(tree.id)

  function findFolder(node: FileSystemNode, id: string): FolderNode | null {
    if (node.type === 'folder') {
      if (node.id === id) return node
      for (const child of node.children) {
        const found = findFolder(child, id)
        if (found) return found
      }
    }
    return null
  }

  function getAllFolders(node: FileSystemNode): FolderNode[] {
    if (node.type === 'file') return []
    return [node, ...node.children.flatMap(getAllFolders)]
  }

  let allFolders = $derived(getAllFolders(tree))

  function addFile() {
    if (!newFileName) return
    const folder = findFolder(tree, selectedFolderId)
    if (!folder) return
    folder.children.push({
      id: genId(),
      name: newFileName,
      type: 'file',
      size: newFileSize,
    })
    folder.expanded = true
    newFileName = ''
  }
</script>

<main>
  <h1>Composite 패턴</h1>
  <p class="desc">
    파일(<strong>Leaf</strong>)과 폴더(<strong>Composite</strong>)를 같은 인터페이스로 다룬다.
    <code>&lt;svelte:self&gt;</code>로 트리를 재귀 렌더링하고, 크기 계산도 재귀로 자동 처리된다.
  </p>

  <div class="stats-bar">
    <span>전체 크기: <strong>{totalSize}</strong></span>
    <span>총 파일 수: <strong>{totalFiles}개</strong></span>
  </div>

  <div class="layout">
    <!-- 파일 트리 (재귀 렌더링) -->
    <section class="card">
      <h2>파일 시스템 트리</h2>
      <!-- 재귀 컴포넌트는 별도 컴포넌트 파일로 구현 (TreeNode.svelte 참조) -->
      <!-- 여기서는 단일 파일 데모를 위해 인라인 재귀 렌더링 함수를 사용 -->
      <div class="tree">
        {#snippet renderNode(node: FileSystemNode, depth: number)}
          <div class="tree-item" style="padding-left: {depth * 1.25}rem">
            {#if node.type === 'folder'}
              <button class="folder-btn" onclick={() => toggleFolder(node)}>
                {node.expanded ? '📂' : '📁'}
                <span class="name">{node.name}/</span>
                <span class="size">{formatSize(getSize(node))}</span>
              </button>
              {#if node.expanded}
                {#each node.children as child}
                  {@render renderNode(child, depth + 1)}
                {/each}
              {/if}
            {:else}
              <div class="file-item">
                <span>📄</span>
                <span class="name">{node.name}</span>
                <span class="size">{formatSize(node.size)}</span>
              </div>
            {/if}
          </div>
        {/snippet}
        {@render renderNode(tree, 0)}
      </div>
    </section>

    <!-- 파일 추가 컨트롤 -->
    <section class="card">
      <h2>파일 추가</h2>
      <label>
        대상 폴더:
        <select bind:value={selectedFolderId}>
          {#each allFolders as folder}
            <option value={folder.id}>{folder.name}/</option>
          {/each}
        </select>
      </label>
      <label>
        파일명:
        <input bind:value={newFileName} placeholder="example.ts" />
      </label>
      <label>
        크기 (bytes):
        <input type="number" bind:value={newFileSize} min="1" />
      </label>
      <button class="btn-primary" onclick={addFile}>파일 추가</button>

      <div class="composite-explain">
        <h3>Composite 패턴의 핵심</h3>
        <ul>
          <li>파일이든 폴더든 <code>getSize()</code>를 같은 방식으로 호출</li>
          <li>폴더는 자식들의 <code>getSize()</code>를 재귀 호출해 합산</li>
          <li>클라이언트는 대상이 파일인지 폴더인지 몰라도 됨</li>
        </ul>
      </div>
    </section>
  </div>

  <div class="explanation">
    <h3>TypeScript vs Svelte 구현 차이</h3>
    <ul>
      <li><strong>TS:</strong> <code>File</code>/<code>Folder</code> 클래스가 <code>FileSystemItem</code> 인터페이스 구현</li>
      <li><strong>Svelte:</strong> 유니온 타입 + <code>{'{#snippet renderNode}'}</code>로 재귀 렌더링 구현</li>
      <li><strong>재귀:</strong> <code>&lt;svelte:self&gt;</code> 또는 <code>{'{#snippet}'}</code>로 자연스러운 재귀 UI 표현 가능</li>
    </ul>
  </div>
</main>

<style>
  main { font-family: sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }
  h1 { color: #059669; margin-bottom: 0.25rem; }
  .desc { color: #64748b; margin-bottom: 1rem; }
  .stats-bar {
    display: flex; gap: 2rem; background: #f0fdf4; border: 1px solid #bbf7d0;
    border-radius: 8px; padding: 0.75rem 1rem; margin-bottom: 1.5rem; font-size: 0.9rem;
  }
  .layout { display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; }
  .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 1.25rem; }
  h2 { font-size: 1rem; margin-top: 0; color: #374151; }
  h3 { font-size: 0.88rem; color: #374151; margin-top: 1.25rem; }
  .tree { font-size: 0.9rem; }
  .tree-item { margin: 0.15rem 0; }
  .folder-btn {
    display: flex; align-items: center; gap: 0.4rem; background: none;
    border: none; cursor: pointer; padding: 0.3rem 0.4rem; border-radius: 5px;
    font-size: 0.9rem; width: 100%; text-align: left;
  }
  .folder-btn:hover { background: #e2e8f0; }
  .file-item { display: flex; align-items: center; gap: 0.4rem; padding: 0.3rem 0.4rem; color: #4b5563; }
  .name { flex: 1; }
  .size { color: #94a3b8; font-size: 0.8rem; }
  label { display: flex; flex-direction: column; gap: 0.25rem; font-size: 0.88rem; color: #374151; margin-bottom: 0.75rem; }
  input, select { padding: 0.4rem 0.6rem; border: 1px solid #cbd5e1; border-radius: 6px; font-size: 0.88rem; }
  .btn-primary { background: #059669; color: white; border: none; padding: 0.5rem 1.2rem; border-radius: 6px; cursor: pointer; font-size: 0.9rem; }
  .btn-primary:hover { background: #047857; }
  .composite-explain { margin-top: 1rem; background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 0.75rem; font-size: 0.85rem; }
  .composite-explain ul { margin: 0.35rem 0 0; padding-left: 1.2rem; }
  .composite-explain li { margin-bottom: 0.3rem; }
  code { background: #e2e8f0; padding: 0.1rem 0.35rem; border-radius: 4px; font-size: 0.8rem; }
  .explanation { margin-top: 2rem; background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 10px; padding: 1rem 1.25rem; font-size: 0.9rem; }
  .explanation ul { margin: 0.5rem 0 0; padding-left: 1.2rem; }
  .explanation li { margin-bottom: 0.4rem; }
</style>
