// patterns/structural/facade/react/App.tsx
/**
 * Facade 패턴 — React 구현
 *
 * React에서의 역할 매핑:
 * - 서브시스템 (TV, Amplifier 등) → 각각의 개별 상태와 제어 훅 (useTV, useAmplifier 등)
 * - Facade (HomeTheaterFacade)    → useHomeTheater() 훅 — 복잡한 서브시스템을 단순한 인터페이스로 통합
 * - Client                        → ControlPanel 컴포넌트 — Facade 훅만 사용
 *
 * 왜 useFacade 훅인가?
 * - TS에서 클라이언트는 HomeTheaterFacade.watchMovie() 하나만 호출하면 됐다.
 * - React에서 useHomeTheater()가 복잡한 상태 관리(TV, 앰프, 스트리밍, 조명)를
 *   하나의 훅으로 추상화해 클라이언트 컴포넌트에게 단순한 API만 노출한다.
 */

import { useState, useCallback } from 'react'

// ─────────────────────────────────────────────
// 서브시스템 상태 타입들
// ─────────────────────────────────────────────

interface TVState { isOn: boolean; input: string; brightness: number }
interface AmpState { isOn: boolean; volume: number; surroundMode: string }
interface StreamingState { isOn: boolean; app: string; content: string }
interface LightsState { isOn: boolean; brightness: number; color: string }

// ─────────────────────────────────────────────
// Facade 훅 — 복잡한 서브시스템을 단순한 인터페이스로 통합
// ─────────────────────────────────────────────

/**
 * useHomeTheater: Facade 패턴을 구현한 커스텀 훅.
 *
 * 클라이언트 컴포넌트에게는 watchMovie(), endMovie() 같은 단순한 메서드만 노출한다.
 * TV, 앰프, 스트리밍, 조명의 복잡한 상태 관리는 모두 이 훅 내부에 숨겨져 있다.
 *
 * 왜 하나의 훅인가?
 * - 클라이언트가 4개의 서브시스템 훅을 따로 import해 초기화 순서를 알아야 한다면
 *   Facade가 없는 것과 다름없다.
 * - useHomeTheater() 하나로 모든 복잡성이 캡슐화된다.
 */
function useHomeTheater() {
  // 각 서브시스템의 상태 (클라이언트에게는 노출되지 않는다)
  const [tv, setTV] = useState<TVState>({ isOn: false, input: 'HDMI1', brightness: 80 })
  const [amp, setAmp] = useState<AmpState>({ isOn: false, volume: 30, surroundMode: '스테레오' })
  const [streaming, setStreaming] = useState<StreamingState>({ isOn: false, app: '', content: '' })
  const [lights, setLights] = useState<LightsState>({ isOn: true, brightness: 100, color: '흰색' })
  const [log, setLog] = useState<string[]>([])

  const addLog = useCallback((msg: string) => {
    setLog(prev => [...prev.slice(-7), `> ${msg}`]) // 최근 8개 유지
  }, [])

  /**
   * watchMovie(): Facade 메서드 — 복잡한 여러 단계를 하나의 호출로 통합.
   *
   * 클라이언트는 이 순서(조명 → TV → 앰프 → 스트리밍)를 알 필요가 없다.
   * 순서가 바뀌거나 단계가 추가되어도 클라이언트 코드는 변경되지 않는다.
   */
  const watchMovie = useCallback((title: string, appName: string = 'Netflix') => {
    addLog('영화 모드 시작...')
    // 1단계: 조명 설정
    setLights({ isOn: true, brightness: 10, color: '주황' })
    addLog('조명: 영화 모드 (주황 10%)')
    // 2단계: TV 켜기
    setTV({ isOn: true, input: 'HDMI1', brightness: 60 })
    addLog('TV: 켜짐, 시네마 모드')
    // 3단계: 앰프 설정
    setAmp({ isOn: true, volume: 40, surroundMode: '돌비 애트모스' })
    addLog('앰프: 돌비 애트모스, 볼륨 40')
    // 4단계: 스트리밍
    setStreaming({ isOn: true, app: appName, content: title })
    addLog(`${appName}: "${title}" 재생 중`)
  }, [addLog])

  /**
   * endMovie(): 모든 기기를 안전하게 종료.
   * 역순으로 종료하는 것이 중요 — 클라이언트가 이 순서를 몰라도 된다.
   */
  const endMovie = useCallback(() => {
    setStreaming({ isOn: false, app: '', content: '' })
    setAmp({ isOn: false, volume: 30, surroundMode: '스테레오' })
    setTV({ isOn: false, input: 'HDMI1', brightness: 80 })
    setLights({ isOn: true, brightness: 80, color: '흰색' })
    addLog('영화 종료, 모든 기기 정리됨')
  }, [addLog])

  /**
   * listenToMusic(): 음악 감상 모드
   */
  const listenToMusic = useCallback((playlist: string) => {
    setLights({ isOn: true, brightness: 60, color: '보라' })
    setAmp({ isOn: true, volume: 60, surroundMode: '스테레오' })
    setStreaming({ isOn: true, app: 'Spotify', content: playlist })
    // TV는 켜지 않는다
    addLog(`음악 모드: "${playlist}" 재생 중`)
  }, [addLog])

  /**
   * shutdownAll(): 전체 시스템 종료
   */
  const shutdownAll = useCallback(() => {
    setStreaming({ isOn: false, app: '', content: '' })
    setAmp({ isOn: false, volume: 30, surroundMode: '스테레오' })
    setTV({ isOn: false, input: 'HDMI1', brightness: 80 })
    setLights({ isOn: false, brightness: 0, color: '흰색' })
    addLog('전체 시스템 종료')
  }, [addLog])

  // Facade가 노출하는 인터페이스 — 단순하고 명확한 메서드들만
  return {
    // 단순화된 Facade 메서드들 (클라이언트 사용)
    watchMovie, endMovie, listenToMusic, shutdownAll,
    // 현재 상태 (모니터링 목적 — 클라이언트가 직접 서브시스템을 제어하지 않는다)
    tv, amp, streaming, lights, log,
  }
}

// ─────────────────────────────────────────────
// 서브시스템 상태 표시 컴포넌트 (읽기 전용)
// ─────────────────────────────────────────────

function SystemStatus({ label, isOn, details }: { label: string; isOn: boolean; details: string }) {
  return (
    <div style={{
      padding: 12, borderRadius: 8, border: `2px solid ${isOn ? '#4caf50' : '#ddd'}`,
      background: isOn ? '#e8f5e9' : '#fafafa', marginBottom: 8,
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        <span style={{ width: 8, height: 8, borderRadius: '50%', background: isOn ? '#4caf50' : '#bdbdbd', display: 'inline-block' }} />
        <strong style={{ fontSize: 13 }}>{label}</strong>
      </div>
      {isOn && <div style={{ fontSize: 12, color: '#555', marginTop: 4 }}>{details}</div>}
    </div>
  )
}

// ─────────────────────────────────────────────
// 메인 App — Facade 훅만 사용하는 클라이언트
// ─────────────────────────────────────────────

export default function App() {
  // 클라이언트: useHomeTheater() 하나만 알면 된다
  const theater = useHomeTheater()
  const [movieTitle, setMovieTitle] = useState('인터스텔라')
  const [playlist, setPlaylist] = useState('재즈 명곡 모음')

  return (
    <div style={{ fontFamily: 'sans-serif', maxWidth: 750, margin: '40px auto', padding: '0 20px' }}>
      <h1 style={{ fontSize: 24, marginBottom: 8 }}>Facade 패턴 — React</h1>
      <p style={{ color: '#666', marginBottom: 24, fontSize: 14 }}>
        <code>useHomeTheater()</code> 하나로 TV, 앰프, 스트리밍, 조명을 통합 제어합니다.<br />
        클라이언트는 복잡한 서브시스템 초기화 순서를 알 필요가 없습니다.
      </p>

      <div style={{ display: 'flex', gap: 20 }}>
        {/* 왼쪽: Facade 컨트롤 */}
        <div style={{ flex: 1 }}>
          <div style={{ fontWeight: 'bold', fontSize: 13, marginBottom: 12 }}>
            Facade 인터페이스 (클라이언트가 사용하는 단순한 메서드들)
          </div>

          {/* 영화 보기 */}
          <div style={{ background: '#f5f5f5', borderRadius: 8, padding: 16, marginBottom: 12 }}>
            <div style={{ fontWeight: 'bold', fontSize: 13, marginBottom: 8 }}>watchMovie()</div>
            <input value={movieTitle} onChange={e => setMovieTitle(e.target.value)}
              placeholder="영화 제목"
              style={{ width: '100%', padding: '8px 12px', border: '1px solid #ddd', borderRadius: 6, boxSizing: 'border-box', marginBottom: 8 }} />
            <div style={{ display: 'flex', gap: 8 }}>
              <button onClick={() => theater.watchMovie(movieTitle, 'Netflix')}
                style={{ flex: 1, padding: '8px', background: '#1976d2', color: 'white', border: 'none', borderRadius: 6, cursor: 'pointer' }}>
                Netflix로 보기
              </button>
              <button onClick={() => theater.watchMovie(movieTitle, 'Watcha')}
                style={{ flex: 1, padding: '8px', background: '#7b1fa2', color: 'white', border: 'none', borderRadius: 6, cursor: 'pointer' }}>
                Watcha로 보기
              </button>
            </div>
          </div>

          {/* 음악 감상 */}
          <div style={{ background: '#f5f5f5', borderRadius: 8, padding: 16, marginBottom: 12 }}>
            <div style={{ fontWeight: 'bold', fontSize: 13, marginBottom: 8 }}>listenToMusic()</div>
            <input value={playlist} onChange={e => setPlaylist(e.target.value)}
              placeholder="플레이리스트"
              style={{ width: '100%', padding: '8px 12px', border: '1px solid #ddd', borderRadius: 6, boxSizing: 'border-box', marginBottom: 8 }} />
            <button onClick={() => theater.listenToMusic(playlist)}
              style={{ width: '100%', padding: '8px', background: '#388e3c', color: 'white', border: 'none', borderRadius: 6, cursor: 'pointer' }}>
              음악 재생
            </button>
          </div>

          {/* 종료 버튼들 */}
          <div style={{ display: 'flex', gap: 8 }}>
            <button onClick={theater.endMovie}
              style={{ flex: 1, padding: '10px', background: '#f57c00', color: 'white', border: 'none', borderRadius: 6, cursor: 'pointer' }}>
              endMovie()
            </button>
            <button onClick={theater.shutdownAll}
              style={{ flex: 1, padding: '10px', background: '#616161', color: 'white', border: 'none', borderRadius: 6, cursor: 'pointer' }}>
              shutdownAll()
            </button>
          </div>

          {/* 로그 */}
          {theater.log.length > 0 && (
            <div style={{ marginTop: 12, background: '#1a1a1a', color: '#4caf50', padding: 12, borderRadius: 6, fontSize: 12, fontFamily: 'monospace' }}>
              {theater.log.map((l, i) => <div key={i}>{l}</div>)}
            </div>
          )}
        </div>

        {/* 오른쪽: 서브시스템 상태 (읽기 전용 모니터링) */}
        <div style={{ width: 220 }}>
          <div style={{ fontWeight: 'bold', fontSize: 13, marginBottom: 12 }}>
            서브시스템 상태 (Facade가 제어)
          </div>
          <SystemStatus label="TV" isOn={theater.tv.isOn}
            details={`입력: ${theater.tv.input} | 밝기: ${theater.tv.brightness}%`} />
          <SystemStatus label="앰프" isOn={theater.amp.isOn}
            details={`볼륨: ${theater.amp.volume} | ${theater.amp.surroundMode}`} />
          <SystemStatus label="스트리밍" isOn={theater.streaming.isOn}
            details={`${theater.streaming.app}: "${theater.streaming.content}"`} />
          <SystemStatus label="조명" isOn={theater.lights.isOn}
            details={`밝기: ${theater.lights.brightness}% | 색상: ${theater.lights.color}`} />
        </div>
      </div>

      <div style={{ background: '#fff8e1', padding: 16, borderRadius: 8, fontSize: 13, marginTop: 16 }}>
        <strong>패턴 포인트:</strong>
        <ul style={{ margin: '8px 0 0', paddingLeft: 20 }}>
          <li><code>useHomeTheater()</code>가 Facade — 4개 서브시스템을 단순한 API로 통합</li>
          <li>클라이언트는 TV/앰프/스트리밍/조명의 초기화 순서를 전혀 모른다</li>
          <li>Facade는 서브시스템을 완전히 숨기지 않는다 — 상태는 읽기 전용으로 노출</li>
          <li>새 기능(프레젠테이션 모드 등) 추가 시 Facade에만 메서드를 추가한다</li>
        </ul>
      </div>
    </div>
  )
}

// patterns/structural/facade/vue/App.vue
<script setup lang="ts">
/**
 * Facade 패턴 — Vue 구현
 *
 * Vue에서의 역할 매핑:
 *   useTV() / useAmplifier() / useStreamingBox() / useLights() → 서브시스템 composables
 *   useHomeTheater() (Facade composable)                        → 복잡한 서브시스템을 하나로 통합
 *   <template>의 버튼들                                          → Client: 퍼사드 메서드만 호출
 *
 * 왜 이렇게 구현하는가?
 *   TypeScript 버전의 HomeTheaterFacade 클래스를 Vue에서는 composable로 표현한다.
 *   각 서브시스템도 개별 composable로 분리해 "복잡한 내부 시스템"을 표현한다.
 *   클라이언트(template)는 watchMovie() 같은 단순 메서드만 호출하면 되고,
 *   내부에서 TV/앰프/스트리밍/조명을 올바른 순서로 제어하는 복잡함은 숨겨진다.
 */

import { reactive, computed } from 'vue'

// ─── 서브시스템 composables ───────────────────────────────────────────────────
// 각각은 자체적으로 복잡한 상태와 API를 가진다.
// 클라이언트가 직접 다루기 어려운 "내부 시스템"이다.

/** TV 서브시스템 */
function useTV() {
  const state = reactive({ isOn: false, input: 'HDMI1', brightness: 80, mode: '일반' })

  return {
    state,
    turnOn() { state.isOn = true },
    turnOff() { state.isOn = false },
    setInput(input: string) {
      if (!state.isOn) throw new Error('TV가 꺼져 있습니다')
      state.input = input
    },
    enableCinemaMode() { state.brightness = 60; state.mode = '시네마' },
    reset() { state.isOn = false; state.input = 'HDMI1'; state.brightness = 80; state.mode = '일반' },
  }
}

/** 앰프 서브시스템 */
function useAmplifier() {
  const state = reactive({ isOn: false, volume: 30, surroundMode: '스테레오' })

  return {
    state,
    turnOn() { state.isOn = true },
    turnOff() { state.isOn = false },
    setVolume(v: number) {
      if (!state.isOn) throw new Error('앰프가 꺼져 있습니다')
      state.volume = Math.max(0, Math.min(100, v))
    },
    setSurroundMode(mode: string) { state.surroundMode = mode },
    reset() { state.isOn = false; state.volume = 30; state.surroundMode = '스테레오' },
  }
}

/** 스트리밍 박스 서브시스템 */
function useStreamingBox() {
  const state = reactive({ isOn: false, app: '', content: '' })

  return {
    state,
    turnOn() { state.isOn = true },
    turnOff() { state.isOn = false; state.content = '' },
    launchApp(app: string) {
      if (!state.isOn) throw new Error('스트리밍 박스가 꺼져 있습니다')
      state.app = app
    },
    play(content: string) { state.content = content },
    stop() { state.content = '' },
    reset() { state.isOn = false; state.app = ''; state.content = '' },
  }
}

/** 스마트 조명 서브시스템 */
function useLights() {
  const state = reactive({ brightness: 100, color: '흰색', isOn: true })

  return {
    state,
    setScene(scene: '영화' | '독서' | '파티' | '수면' | '기본') {
      const scenes = {
        영화:  { brightness: 10,  color: '주황' },
        독서:  { brightness: 80,  color: '흰색' },
        파티:  { brightness: 60,  color: '보라' },
        수면:  { brightness: 0,   color: '흰색' },
        기본:  { brightness: 100, color: '흰색' },
      }
      const s = scenes[scene]
      state.brightness = s.brightness
      state.color = s.color
      state.isOn = s.brightness > 0
    },
    turnOn() { state.brightness = 100; state.isOn = true },
    turnOff() { state.brightness = 0; state.isOn = false },
  }
}

// ─── Facade composable ────────────────────────────────────────────────────────
/**
 * useHomeTheater: 홈시어터 퍼사드
 *
 * 복잡한 서브시스템 composable들을 내부에 보유하고
 * 클라이언트에게 단순한 메서드(watchMovie, endMovie 등)만 노출한다.
 * 서브시스템 간의 순서 의존성은 여기서 관리한다.
 */
function useHomeTheater() {
  const tv = useTV()
  const amp = useAmplifier()
  const streaming = useStreamingBox()
  const lights = useLights()

  // 실행 로그: 퍼사드가 내부적으로 어떤 단계를 수행하는지 시각화
  const log = reactive<string[]>([])

  function addLog(msg: string) { log.unshift(msg) }

  /**
   * 영화 보기: 여러 단계를 하나의 메서드로 통합
   * 클라이언트는 이 한 줄만 호출하면 된다.
   */
  function watchMovie(title: string, app = 'Netflix') {
    log.length = 0
    addLog(`▶ watchMovie("${title}") 시작`)
    // 1. 조명 설정
    lights.setScene('영화')
    addLog('  조명 → 영화 모드 (주황, 10%)')
    // 2. TV 설정 (순서 중요: 켜기 → 모드 → 입력)
    tv.turnOn()
    tv.enableCinemaMode()
    tv.setInput('HDMI1')
    addLog('  TV → 켜기, 시네마 모드, HDMI1 입력')
    // 3. 앰프 설정
    amp.turnOn()
    amp.setSurroundMode('돌비 애트모스')
    amp.setVolume(40)
    addLog('  앰프 → 켜기, 돌비 애트모스, 볼륨 40')
    // 4. 스트리밍
    streaming.turnOn()
    streaming.launchApp(app)
    streaming.play(title)
    addLog(`  스트리밍 → ${app} 실행, "${title}" 재생`)
    addLog(`✓ 영화 준비 완료!`)
  }

  /** 영화 종료: 역순으로 안전하게 끈다 */
  function endMovie() {
    log.length = 0
    addLog('■ endMovie() 시작')
    streaming.stop()
    streaming.turnOff()
    addLog('  스트리밍 → 정지 후 끄기')
    amp.turnOff()
    addLog('  앰프 → 끄기')
    tv.turnOff()
    addLog('  TV → 끄기')
    lights.setScene('기본')
    addLog('  조명 → 기본 모드 복귀')
    addLog('✓ 영화 종료 완료')
  }

  /** 음악 감상 모드 */
  function listenToMusic(playlist: string) {
    log.length = 0
    addLog(`♪ listenToMusic("${playlist}") 시작`)
    lights.setScene('파티')
    addLog('  조명 → 파티 모드')
    amp.turnOn()
    amp.setSurroundMode('스테레오')
    amp.setVolume(60)
    addLog('  앰프 → 켜기, 스테레오, 볼륨 60')
    streaming.turnOn()
    streaming.launchApp('Spotify')
    streaming.play(playlist)
    addLog(`  스트리밍 → Spotify, "${playlist}" 재생`)
    addLog('✓ 음악 재생 중!')
  }

  /** 전체 종료 */
  function shutdownAll() {
    log.length = 0
    addLog('⏻ shutdownAll() 시작')
    streaming.turnOff()
    amp.turnOff()
    tv.turnOff()
    lights.turnOff()
    addLog('  모든 기기 종료')
    addLog('✓ 시스템 전체 종료')
  }

  return { tv, amp, streaming, lights, log, watchMovie, endMovie, listenToMusic, shutdownAll }
}

// ─── 인스턴스화 ───────────────────────────────────────────────────────────────
const theater = useHomeTheater()
const movieTitle = { value: '인터스텔라' }
const playlist = { value: '팝 베스트 100' }
</script>

<template>
  <div style="font-family: sans-serif; max-width: 750px; margin: 2rem auto; padding: 0 1rem;">
    <h1 style="border-bottom: 2px solid #333; padding-bottom: 0.5rem;">Facade 패턴</h1>
    <p style="color: #555;">
      <code>useHomeTheater()</code>가 퍼사드다. TV/앰프/스트리밍/조명 4개의 복잡한 서브시스템을 내부에 보유하고,
      클라이언트에게는 <code>watchMovie()</code> 같은 단순 메서드만 노출한다.
    </p>

    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem;">
      <!-- 클라이언트 컨트롤 (Facade 메서드만 사용) -->
      <div>
        <div style="border: 1px solid #ddd; border-radius: 8px; padding: 1rem; margin-bottom: 1rem;">
          <h3 style="margin-top: 0; color: #2b6cb0;">Client — 퍼사드 메서드 호출</h3>
          <div style="margin-bottom: 0.75rem;">
            <input v-model="movieTitle.value" placeholder="영화 제목" style="width: 100%; box-sizing: border-box; padding: 6px; border: 1px solid #ccc; border-radius: 4px; margin-bottom: 6px;" />
            <button @click="theater.watchMovie(movieTitle.value)"
              style="width: 100%; padding: 8px; background: #2b6cb0; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 0.95rem; margin-bottom: 4px;">
              🎬 watchMovie()
            </button>
            <button @click="theater.endMovie()"
              style="width: 100%; padding: 8px; background: #718096; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 0.95rem;">
              ⏹ endMovie()
            </button>
          </div>
          <div style="margin-bottom: 0.75rem;">
            <input v-model="playlist.value" placeholder="플레이리스트" style="width: 100%; box-sizing: border-box; padding: 6px; border: 1px solid #ccc; border-radius: 4px; margin-bottom: 6px;" />
            <button @click="theater.listenToMusic(playlist.value)"
              style="width: 100%; padding: 8px; background: #276749; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 0.95rem;">
              🎵 listenToMusic()
            </button>
          </div>
          <button @click="theater.shutdownAll()"
            style="width: 100%; padding: 8px; background: #c53030; color: white; border: none; border-radius: 4px; cursor: pointer; font-size: 0.95rem;">
            ⏻ shutdownAll()
          </button>
        </div>

        <!-- 퍼사드 실행 로그 -->
        <div v-if="theater.log.length" style="border: 1px solid #ddd; border-radius: 8px; padding: 1rem;">
          <h3 style="margin-top: 0; font-size: 0.9rem;">퍼사드 내부 실행 순서</h3>
          <div v-for="(entry, i) in [...theater.log].reverse()" :key="i"
            style="font-size: 0.8rem; font-family: monospace; padding: 2px 0; color: #333;">
            {{ entry }}
          </div>
        </div>
      </div>

      <!-- 서브시스템 상태 (복잡한 내부 — 클라이언트가 직접 다루지 않아도 됨) -->
      <div>
        <h3 style="margin-top: 0; color: #718096;">서브시스템 상태 (내부)</h3>

        <div v-for="(label, key) in {tv: 'TV', amp: '앰프', streaming: '스트리밍', lights: '조명'}" :key="key"
          :style="{
            border: '1px solid #ddd', borderRadius: '6px', padding: '0.75rem',
            marginBottom: '0.5rem',
            background: (theater as any)[key].state.isOn ? '#f0fff4' : '#f5f5f5',
          }">
          <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.25rem;">
            <strong style="font-size: 0.9rem;">{{ label }}</strong>
            <span :style="{ fontSize: '0.8rem', color: (theater as any)[key].state.isOn ? '#276749' : '#718096' }">
              {{ (theater as any)[key].state.isOn ? '켜짐' : '꺼짐' }}
            </span>
          </div>
          <div style="font-size: 0.75rem; color: #555; font-family: monospace;">
            <template v-if="key === 'tv'">
              입력: {{ theater.tv.state.input }} | 밝기: {{ theater.tv.state.brightness }}% | {{ theater.tv.state.mode }}
            </template>
            <template v-else-if="key === 'amp'">
              볼륨: {{ theater.amp.state.volume }} | {{ theater.amp.state.surroundMode }}
            </template>
            <template v-else-if="key === 'streaming'">
              앱: {{ theater.streaming.state.app || '-' }} | 재생: {{ theater.streaming.state.content || '-' }}
            </template>
            <template v-else>
              밝기: {{ theater.lights.state.brightness }}% | {{ theater.lights.state.color }}
            </template>
          </div>
        </div>

        <div style="margin-top: 0.5rem; padding: 0.5rem; background: #fffbeb; border-radius: 4px; font-size: 0.8rem; color: #744210;">
          클라이언트는 이 4개의 서브시스템을 직접 다루지 않아도 됩니다.
          퍼사드 메서드 하나로 모든 설정이 완료됩니다.
        </div>
      </div>
    </div>
  </div>
</template>
